#ifndef RESOURCES_H
#define RESOURCES_H

#define OK -1
#define SPECIFIED_NODE_NOT_FOUND 0
#define SPECIFIED_NODE_ALREADY_EXISTS 1
#define SPECIFIED_NODE_FROM_NOT_FOUND 2
#define SPECIFIED_NODE_TO_NOT_FOUND 3
#define SPECIFIED_EDGE_NOT_FOUND 4
#define SPECIFIED_EDGE_ALREADY_EXISTS 5
#define EMPTY_NODE_NAME 6

#endif // RESOURCES_H
